
javascripts:
  - 'lib/jquery.js'
  - 'lib/underscore.js'
  - 'lib/backbone.js'
  - 'app/routers/*.coffee'
  - 'app/views/**/*.coffee'
  - 'app/models/*.coffee'

stylesheets:
  - 'stylesheets/application.less'

specs:
  - 'spec/*/*.coffee'
  - 'spec/views/*/*.coffee'
  
fixtures:
  
templates:
  - 'app/templates/*.eco'
  - 'app/templates/*/*.eco'